"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import {
  AlertTriangle,
  ArrowLeft,
  ArrowUpRight,
  Bot,
  Calendar,
  ChevronDown,
  CheckCircle2,
  Clock,
  Download,
  FileBarChart2,
  FileText,
  Lightbulb,
  MapPin,
  MessageSquare,
  TrendingUp,
  Zap,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { api, type TimelineDay, type WeeklyReport } from "@/lib/api";
import { cn } from "@/lib/utils";
import { toUserFacingError } from "@/lib/user-facing-errors";
import { useAuth } from "@/providers/AuthProvider";
import { useDashboardLive } from "@/providers/DashboardLiveProvider";
import { deriveSystemHealthTone, type SystemHealthTone } from "@/lib/system-health";

/* ─── helpers ─── */

function formatHours(value: number | null) {
  if (value === null) return "n/a";
  if (value < 24) return `${value.toFixed(1)}h`;
  return `${(value / 24).toFixed(1)}d`;
}

function formatWeekRange(start: string, end: string) {
  const s = new Date(start);
  const e = new Date(end);
  return `${s.toLocaleDateString(undefined, { month: "short", day: "numeric" })} — ${e.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" })}`;
}

function buildReportText(report: WeeklyReport) {
  return [
    "══════════════════════════════════════════════",
    "       AgenticPulse – Weekly Product Insight Report",
    "══════════════════════════════════════════════",
    "",
    `Period: ${report.weekStart} to ${report.weekEnd}`,
    `Generated: ${new Date().toLocaleDateString()}`,
    `Mode: ${report.generation_mode === "ai" ? "AI Summary (Groq)" : "Rule-Based Summary"}`,
    "",
    "──────────────────────────────────────────────",
    "  1. EXECUTIVE SUMMARY",
    "──────────────────────────────────────────────",
    "",
    report.summary,
    "",
    "──────────────────────────────────────────────",
    "  2. KEY METRICS",
    "──────────────────────────────────────────────",
    "",
    `  Total Feedback:       ${report.metrics.total_feedback_count}`,
    `  Issue Events:         ${report.metrics.total_issue_count}`,
    `  Unresolved Issues:    ${report.metrics.unresolved_issue_count}`,
    `  Avg Resolution Time:  ${formatHours(report.metrics.avg_resolution_time)}`,
    `  Resolved Count:       ${report.resolution.resolved_count}`,
    `  Resolution Rate:      ${report.resolution.resolution_efficiency === null ? "n/a" : `${report.resolution.resolution_efficiency}%`}`,
    "",
    "──────────────────────────────────────────────",
    "  3. TOP ISSUES",
    "──────────────────────────────────────────────",
    "",
    ...(report.top_issues.length > 0
      ? report.top_issues.map(
          (issue, i) =>
            `  ${i + 1}. ${issue.title}\n     Reports: ${issue.report_count} | Priority: ${issue.priority} | Trend: ${issue.trend_percent}%`
        )
      : ["  No issue clusters this week."]),
    "",
    "──────────────────────────────────────────────",
    "  4. AI INSIGHTS",
    "──────────────────────────────────────────────",
    "",
    ...(report.insights.length > 0
      ? report.insights.map((item) => `  • ${item}`)
      : ["  • No notable insights surfaced."]),
    "",
    "──────────────────────────────────────────────",
    "  5. SPIKE DAYS",
    "──────────────────────────────────────────────",
    "",
    ...(report.spikes.length > 0
      ? report.spikes.map(
          (spike) =>
            `  ⚠  ${spike.date} — ${spike.issue_count} issues, ${spike.feedback_count} feedback events (${spike.severity})`
        )
      : ["  No major spikes this week."]),
    "",
    "──────────────────────────────────────────────",
    "  6. RECOMMENDATIONS",
    "──────────────────────────────────────────────",
    "",
    ...(report.recommendations.length > 0
      ? report.recommendations.map((item, i) => `  ${i + 1}. ${item}`)
      : ["  No recommendations yet."]),
    "",
    "──────────────────────────────────────────────",
    "  7. TOP LOCATIONS",
    "──────────────────────────────────────────────",
    "",
    ...(report.locations.length > 0
      ? report.locations.map((loc) => `  • ${loc.name}: ${loc.count}`)
      : ["  No location signal this week."]),
    "",
    "══════════════════════════════════════════════",
    "  Generated by AgenticPulse",
    "══════════════════════════════════════════════",
  ].join("\n");
}

function SectionHeading({
  icon: Icon,
  title,
  tone = "bad",
}: {
  icon: React.ElementType;
  title: string;
  tone?: SystemHealthTone;
}) {
  const cls =
    tone === "good"
      ? "text-emerald-600 dark:text-emerald-400"
      : tone === "warning"
        ? "text-amber-600 dark:text-amber-400"
        : "text-red-600 dark:text-red-400";
  return (
    <div className="flex items-center gap-3">
      <div className={cn("flex h-9 w-9 items-center justify-center rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent", cls)}>
        <Icon className="h-4 w-4" />
      </div>
      <h2 className="text-lg font-semibold text-slate-900 dark:text-white tracking-tight">{title}</h2>
    </div>
  );
}

/* ─── page ─── */

export default function WeeklyReportsPage() {
  const { session } = useAuth();
  const { criticalAlerts } = useDashboardLive();
  const [days, setDays] = useState<TimelineDay[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const [selectedWeekEnd, setSelectedWeekEnd] = useState<string | null>(null);
  const [report, setReport] = useState<WeeklyReport | null>(null);
  const [reportLoading, setReportLoading] = useState(false);
  const [reportError, setReportError] = useState<string | null>(null);

  const [copyState, setCopyState] = useState<"idle" | "copied">("idle");
  const [calendarOpen, setCalendarOpen] = useState(false);

  const chromeTone = deriveSystemHealthTone(criticalAlerts);
  const headingTone: SystemHealthTone = chromeTone === "good" ? "good" : chromeTone === "warning" ? "warning" : "bad";
  const neutralButtonTone =
    "border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent text-slate-700 dark:text-slate-200 hover:border-slate-300 dark:hover:border-slate-700 hover:bg-slate-50 dark:hover:bg-white/[0.04]";
  const activeButtonTone =
    chromeTone === "good"
      ? "border-emerald-200 dark:border-emerald-500/20 bg-emerald-50 dark:bg-emerald-500/10 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-100 dark:hover:bg-emerald-500/15"
      : chromeTone === "warning"
        ? "border-amber-200 dark:border-amber-500/20 bg-amber-50 dark:bg-amber-500/10 text-amber-700 dark:text-amber-300 hover:bg-amber-100 dark:hover:bg-amber-500/15"
        : "border-red-200 dark:border-red-500/20 bg-red-50 dark:bg-red-500/10 text-red-700 dark:text-red-300 hover:bg-red-100 dark:hover:bg-red-500/15";

  /* ─── load timeline to build week list ─── */

  useEffect(() => {
    const loadTimeline = async () => {
      if (!session?.access_token) { setDays([]); setLoading(false); return; }
      setLoading(true); setError(null);
      try { const result = await api.timeline.list(session.access_token); setDays(result); }
      catch (err) { setError(toUserFacingError(err, "timeline-load")); }
      finally { setLoading(false); }
    };
    void loadTimeline();
  }, [session?.access_token]);

  /* ─── build week cards ─── */

  const weeks = useMemo(() => {
    if (days.length === 0) return [];
    const sorted = [...days].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
    const groups: Array<{ weekStart: string; weekEnd: string; days: TimelineDay[]; totalFeedback: number; totalIssues: number; topSeverity: string }> = [];

    let weekDays: TimelineDay[] = [];
    let weekStartDate: Date | null = null;

    sorted.forEach((day) => {
      const d = new Date(day.date);
      if (!weekStartDate) {
        weekStartDate = d;
        weekDays = [day];
      } else if (d.getTime() - weekStartDate.getTime() < 7 * 24 * 60 * 60 * 1000) {
        weekDays.push(day);
      } else {
        groups.push({
          weekStart: weekDays[0].date,
          weekEnd: weekDays[weekDays.length - 1].date,
          days: weekDays,
          totalFeedback: weekDays.reduce((s, d) => s + d.feedback_count, 0),
          totalIssues: weekDays.reduce((s, d) => s + d.issue_count, 0),
          topSeverity: weekDays.some((d) => d.severity === "red") ? "red" : weekDays.some((d) => d.severity === "yellow") ? "yellow" : "green",
        });
        weekStartDate = d;
        weekDays = [day];
      }
    });

    if (weekDays.length > 0) {
      groups.push({
        weekStart: weekDays[0].date,
        weekEnd: weekDays[weekDays.length - 1].date,
        days: weekDays,
        totalFeedback: weekDays.reduce((s, d) => s + d.feedback_count, 0),
        totalIssues: weekDays.reduce((s, d) => s + d.issue_count, 0),
        topSeverity: weekDays.some((d) => d.severity === "red") ? "red" : weekDays.some((d) => d.severity === "yellow") ? "yellow" : "green",
      });
    }

    return groups.reverse();
  }, [days]);

  const selectedWeek = useMemo(
    () => weeks.find((week) => week.weekEnd === selectedWeekEnd) ?? null,
    [selectedWeekEnd, weeks]
  );

  const dateOptions = useMemo(
    () =>
      [...days]
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
        .map((day) => {
          const matchingWeek =
            weeks.find(
              (week) =>
                new Date(day.date).getTime() >= new Date(week.weekStart).getTime() &&
                new Date(day.date).getTime() <= new Date(week.weekEnd).getTime()
            ) ?? null;

          return {
            ...day,
            matchingWeekEnd: matchingWeek?.weekEnd ?? null,
            matchingWeekLabel: matchingWeek
              ? formatWeekRange(matchingWeek.weekStart, matchingWeek.weekEnd)
              : null,
          };
        }),
    [days, weeks]
  );

  const selectedCalendarLabel = selectedWeek
    ? formatWeekRange(selectedWeek.weekStart, selectedWeek.weekEnd)
    : "Choose a week by date";

  const getSeverityClasses = (severity: string) =>
    severity === "green"
      ? "border-emerald-200 dark:border-emerald-500/20 bg-emerald-50 dark:bg-emerald-500/10 text-emerald-700 dark:text-emerald-300"
      : severity === "yellow"
        ? "border-amber-200 dark:border-amber-500/20 bg-amber-50 dark:bg-amber-500/10 text-amber-700 dark:text-amber-300"
        : "border-red-200 dark:border-red-500/20 bg-red-50 dark:bg-red-500/10 text-red-700 dark:text-red-300";

  /* ─── load selected week report ─── */

  useEffect(() => {
    const loadReport = async () => {
      if (!session?.access_token || !selectedWeekEnd) { setReport(null); setReportLoading(false); return; }
      setReportLoading(true); setReportError(null);
      try { const result = await api.reports.weekly(session.access_token, selectedWeekEnd); setReport(result); }
      catch (err) { setReportError(toUserFacingError(err, "weekly-report-load")); }
      finally { setReportLoading(false); }
    };
    void loadReport();
  }, [selectedWeekEnd, session?.access_token]);

  /* ─── downloads ─── */

  const handleDownloadTxt = () => {
    if (!report) return;
    const blob = new Blob([buildReportText(report)], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `agenticpulse-report-${report.weekEnd}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = () => {
    if (!report) return;
    // PDF: using printable HTML rendered and browser print as PDF
    const content = buildReportText(report);
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>AgenticPulse Weekly Report – ${report.weekEnd}</title>
        <style>
          body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1e293b; line-height: 1.8; font-size: 13px; }
          pre { white-space: pre-wrap; word-wrap: break-word; font-family: inherit; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body><pre>${content.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre></body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 300);
  };

  const handleCopy = async () => {
    if (!report) return;
    await navigator.clipboard.writeText(buildReportText(report));
    setCopyState("copied");
    window.setTimeout(() => setCopyState("idle"), 1800);
  };

  const selectDate = (weekEnd: string | null) => {
    if (!weekEnd) {
      return;
    }

    setSelectedWeekEnd(weekEnd);
    setCalendarOpen(false);
  };

  /* ─── view: full report ─── */

  if (selectedWeekEnd) {
    return (
      <div className="space-y-10">
        <div className="relative">
          <Button
            variant="outline"
            onClick={() => setCalendarOpen((current) => !current)}
            className={cn("gap-2", neutralButtonTone)}
          >
            <Calendar className="h-4 w-4" />
            {selectedCalendarLabel}
            <ChevronDown className={cn("h-4 w-4 transition-transform", calendarOpen ? "rotate-180" : "")} />
          </Button>

          <AnimatePresence>
            {calendarOpen ? (
              <motion.div
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 4 }}
                transition={{ duration: 0.18 }}
                className="absolute left-0 top-full z-20 mt-3 w-full max-w-3xl rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0b0b0b] p-4 shadow-2xl"
              >
                <div className="mb-3 flex items-center justify-between gap-3">
                  <div>
                    <p className="text-sm font-semibold text-slate-900 dark:text-white">
                      Jump to weekly report
                    </p>
                    <p className="text-xs text-slate-500 dark:text-slate-400">
                      Dates inherit issue severity so you can spot heavier weeks fast.
                    </p>
                  </div>
                  <Button variant="ghost" size="sm" onClick={() => setCalendarOpen(false)}>
                    Close
                  </Button>
                </div>
                <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
                  {dateOptions.map((day) => (
                    <button
                      key={day.date}
                      type="button"
                      onClick={() => selectDate(day.matchingWeekEnd)}
                      disabled={!day.matchingWeekEnd}
                      className={cn(
                        "rounded-xl border p-3 text-left transition-all",
                        getSeverityClasses(day.severity),
                        day.matchingWeekEnd
                          ? "hover:translate-y-[-1px]"
                          : "cursor-not-allowed opacity-60",
                        selectedWeekEnd === day.matchingWeekEnd ? "ring-2 ring-current/20" : ""
                      )}
                    >
                      <p className="text-sm font-semibold">
                        {new Date(day.date).toLocaleDateString(undefined, {
                          month: "short",
                          day: "numeric",
                        })}
                      </p>
                      <p className="mt-1 text-xs opacity-80">
                        {day.issue_count} issues • {day.feedback_count} feedback
                      </p>
                      <p className="mt-2 text-[11px] uppercase tracking-[0.14em] opacity-75">
                        {day.matchingWeekLabel || "No week"}
                      </p>
                    </button>
                  ))}
                </div>
              </motion.div>
            ) : null}
          </AnimatePresence>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={() => { setSelectedWeekEnd(null); setReport(null); }}
            className={cn(
              "flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-medium transition",
              neutralButtonTone
            )}
          >
            <ArrowLeft className="h-4 w-4" /> Back to reports
          </button>
        </div>

        {reportLoading ? (
          <div className="space-y-5">
            <Skeleton className="h-32 rounded-2xl bg-slate-100 dark:bg-slate-800" />
            <div className="grid gap-4 md:grid-cols-4">
              {Array.from({ length: 4 }).map((_, i) => (
                <Skeleton key={i} className="h-20 rounded-2xl bg-slate-100 dark:bg-slate-800" />
              ))}
            </div>
            <Skeleton className="h-64 rounded-2xl bg-slate-100 dark:bg-slate-800" />
          </div>
        ) : reportError ? (
          <div className="rounded-2xl border border-red-200 dark:border-rose-500/20 bg-red-50 dark:bg-rose-500/10 p-6 text-sm text-red-600 dark:text-rose-300">{reportError}</div>
        ) : !report ? (
          <div className="rounded-2xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-transparent p-6 text-sm text-slate-500 dark:text-slate-400">
            Weekly insights will appear here once AgenticPulse has enough data for the selected range.
          </div>
        ) : (
          <>
            {/* ── Header + Downloads ── */}
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <SectionHeading icon={FileBarChart2} title="Weekly Product Insight Report" tone={headingTone} />
                <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{formatWeekRange(report.weekStart, report.weekEnd)}</p>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className={cn(
                  "text-[10px]",
                  report.generation_mode === "ai"
                    ? "text-emerald-600 dark:text-emerald-300 border-emerald-200 dark:border-emerald-500/20"
                    : "text-amber-600 dark:text-amber-300 border-amber-200 dark:border-amber-500/20"
                )}>
                  {report.generation_mode === "ai" ? "AI Summary" : "Rule Summary"}
                </Badge>
              </div>
            </div>

            {/* Download buttons */}
            <div className="flex flex-wrap items-center gap-3">
              <Button variant="outline" size="sm" onClick={handleDownloadPdf} className={cn("transition-colors", activeButtonTone)}>
                <Download className="h-4 w-4" /> Download as PDF
              </Button>
              <Button variant="outline" size="sm" onClick={handleDownloadTxt} className={cn("transition-colors", neutralButtonTone)}>
                <FileText className="h-4 w-4" /> Download as TXT
              </Button>
              <Button variant="outline" size="sm" onClick={() => void handleCopy()} className={cn("transition-colors", copyState === "copied" ? activeButtonTone : neutralButtonTone)}>
                {copyState === "copied" ? <CheckCircle2 className="h-4 w-4 text-emerald-500" /> : <FileText className="h-4 w-4" />}
                {copyState === "copied" ? "Copied!" : "Copy to clipboard"}
              </Button>
            </div>

            {/* ── 1. Summary ── */}
            <div className="rounded-2xl border border-emerald-200 dark:border-emerald-500/15 bg-emerald-50 dark:bg-emerald-500/5 p-5 transition-colors">
              <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.2em] text-emerald-600 dark:text-emerald-400 mb-3">
                <Bot className="h-3.5 w-3.5" /> Executive Summary
              </div>
              <p className="text-sm leading-7 text-slate-700 dark:text-slate-200">{report.summary}</p>
            </div>

            {/* ── 2. Key Metrics ── */}
            <div className="grid gap-4 grid-cols-2 lg:grid-cols-4">
              <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent p-5">
                <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500">
                  <MessageSquare className="h-3.5 w-3.5" /> Feedback
                </div>
                <p className="mt-3 text-2xl font-bold text-slate-900 dark:text-white">{report.metrics.total_feedback_count}</p>
              </div>
              <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent p-5">
                <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500">
                  <AlertTriangle className="h-3.5 w-3.5" /> Issues
                </div>
                <p className="mt-3 text-2xl font-bold text-slate-900 dark:text-white">{report.metrics.total_issue_count}</p>
              </div>
              <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent p-5">
                <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500">
                  <Clock className="h-3.5 w-3.5" /> Resolution
                </div>
                <p className="mt-3 text-2xl font-bold text-slate-900 dark:text-white">{formatHours(report.metrics.avg_resolution_time)}</p>
              </div>
              <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent p-5">
                <div className="flex items-center gap-2 text-[11px] uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500">
                  <Zap className="h-3.5 w-3.5" /> Efficiency
                </div>
                <p className="mt-3 text-2xl font-bold text-slate-900 dark:text-white">
                  {report.resolution.resolution_efficiency === null ? "n/a" : `${report.resolution.resolution_efficiency}%`}
                </p>
              </div>
            </div>

            {/* ── 3. Top Issues ── */}
            <section className="space-y-4">
              <SectionHeading icon={TrendingUp} title="Top Issues" tone={headingTone} />
              {report.top_issues.length > 0 ? (
                <div className="space-y-3">
                  {report.top_issues.map((issue) => (
                    <Link
                      key={issue.id}
                      href={`/dashboard/issues/${issue.id}`}
                      className="block rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent p-4 transition-colors hover:border-slate-300 dark:hover:border-slate-700 hover:bg-slate-50 dark:hover:bg-white/[0.02]"
                    >
                      <div className="flex items-center justify-between gap-3">
                        <p className="text-sm font-medium text-slate-900 dark:text-white">{issue.title}</p>
                        <div className="flex items-center gap-2">
                          <Badge variant="outline" className="text-[10px]">{issue.priority}</Badge>
                          <span className="text-xs text-slate-400 dark:text-slate-500">{issue.report_count} reports</span>
                        </div>
                      </div>
                      <div className="mt-2 flex items-center gap-3 text-xs text-slate-500 dark:text-slate-400">
                        <span>{issue.category}</span>
                        <span className={issue.trend_percent > 0 ? "text-red-600 dark:text-red-400" : "text-emerald-600 dark:text-emerald-400"}>
                          {issue.trend_percent > 0 ? "+" : ""}{issue.trend_percent}% trend
                        </span>
                      </div>
                    </Link>
                  ))}
                </div>
              ) : (
                <div className="rounded-2xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-transparent p-5 text-sm text-slate-500 dark:text-slate-400">
                  No issue clusters this week.
                </div>
              )}
            </section>

            {/* ── 4. AI Insights ── */}
            <section className="space-y-4">
              <SectionHeading icon={Lightbulb} title="AI Insights" tone={headingTone} />
              {report.insights.length > 0 ? (
                <div className="space-y-3">
                  {report.insights.map((insight) => (
                    <div key={insight} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent p-4 text-sm text-slate-700 dark:text-slate-300 transition-colors">
                      {insight}
                    </div>
                  ))}
                </div>
              ) : (
                <div className="rounded-2xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-transparent p-5 text-sm text-slate-500 dark:text-slate-400">
                  No notable insights surfaced for this week.
                </div>
              )}
            </section>

            {/* ── 5. Spike Days ── */}
            {report.spikes.length > 0 && (
              <section className="space-y-4">
                <SectionHeading icon={AlertTriangle} title="Spike Days" tone={headingTone} />
                <div className="grid gap-3 md:grid-cols-2">
                  {report.spikes.map((spike) => (
                    <div key={spike.date} className="rounded-2xl border border-amber-200 dark:border-amber-500/20 bg-amber-50 dark:bg-amber-500/5 p-4 transition-colors">
                      <div className="flex items-center justify-between gap-3">
                        <p className="text-sm font-semibold text-slate-900 dark:text-white">{spike.date}</p>
                        <Badge variant="outline" className="text-[10px] text-amber-600 dark:text-amber-400 border-amber-200 dark:border-amber-500/20">{spike.severity}</Badge>
                      </div>
                      <p className="mt-2 text-xs text-slate-600 dark:text-slate-400">
                        {spike.issue_count} issues • {spike.feedback_count} feedback events
                      </p>
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* ── 6. Recommendations ── */}
            <section className="space-y-4">
              <SectionHeading icon={CheckCircle2} title="Recommendations" tone={headingTone} />
              {report.recommendations.length > 0 ? (
                <div className="space-y-3">
                  {report.recommendations.map((item, i) => (
                    <div key={item} className="rounded-2xl border border-emerald-200 dark:border-emerald-500/15 bg-emerald-50 dark:bg-emerald-500/5 p-4 text-sm text-slate-700 dark:text-slate-300 transition-colors">
                      <span className="font-medium text-emerald-700 dark:text-emerald-400 mr-2">{i + 1}.</span>
                      {item}
                    </div>
                  ))}
                </div>
              ) : (
                <div className="rounded-2xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-transparent p-5 text-sm text-slate-500 dark:text-slate-400">
                  No recommendations yet.
                </div>
              )}
            </section>

            {/* ── 7. Locations ── */}
            {report.locations.length > 0 && (
              <section className="space-y-4">
                <SectionHeading icon={MapPin} title="Top Locations" tone={headingTone} />
                <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
                  {report.locations.map((loc) => (
                    <div key={loc.name} className="flex items-center justify-between rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent p-4 transition-colors">
                      <p className="text-sm font-medium text-slate-900 dark:text-white">{loc.name}</p>
                      <span className="text-sm text-slate-500 dark:text-slate-400">{loc.count}</span>
                    </div>
                  ))}
                </div>
              </section>
            )}
          </>
        )}
      </div>
    );
  }

  /* ─── view: week list ─── */

  return (
    <div className="space-y-10">
      <section className="space-y-5">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <SectionHeading icon={FileBarChart2} title="Weekly Reports" tone={headingTone} />
            <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">
              Structured intelligence briefs generated from your product data. Click any week to expand the full report.
            </p>
          </div>

          <div className="relative">
            <Button
              variant="outline"
              onClick={() => setCalendarOpen((current) => !current)}
              className={cn("gap-2", neutralButtonTone)}
            >
              <Calendar className="h-4 w-4" />
              {selectedCalendarLabel}
              <ChevronDown className={cn("h-4 w-4 transition-transform", calendarOpen ? "rotate-180" : "")} />
            </Button>

            <AnimatePresence>
              {calendarOpen ? (
                <motion.div
                  initial={{ opacity: 0, y: 8 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: 4 }}
                  transition={{ duration: 0.18 }}
                  className="absolute right-0 top-full z-20 mt-3 w-[min(92vw,52rem)] rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0b0b0b] p-4 shadow-2xl"
                >
                  <div className="mb-3 flex items-center justify-between gap-3">
                    <div>
                      <p className="text-sm font-semibold text-slate-900 dark:text-white">
                        Pick a date to open its weekly report
                      </p>
                      <p className="text-xs text-slate-500 dark:text-slate-400">
                        Green means calmer days, yellow means active, red means issue-heavy.
                      </p>
                    </div>
                    <Button variant="ghost" size="sm" onClick={() => setCalendarOpen(false)}>
                      Close
                    </Button>
                  </div>
                  <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">
                    {dateOptions.map((day) => (
                      <button
                        key={day.date}
                        type="button"
                        onClick={() => selectDate(day.matchingWeekEnd)}
                        disabled={!day.matchingWeekEnd}
                        className={cn(
                          "rounded-xl border p-3 text-left transition-all",
                          getSeverityClasses(day.severity),
                          day.matchingWeekEnd
                            ? "hover:translate-y-[-1px]"
                            : "cursor-not-allowed opacity-60",
                          selectedWeekEnd === day.matchingWeekEnd ? "ring-2 ring-current/20" : ""
                        )}
                      >
                        <p className="text-sm font-semibold">
                          {new Date(day.date).toLocaleDateString(undefined, {
                            weekday: "short",
                            month: "short",
                            day: "numeric",
                          })}
                        </p>
                        <p className="mt-1 text-xs opacity-80">
                          {day.issue_count} issues • {day.feedback_count} feedback
                        </p>
                        <p className="mt-2 text-[11px] uppercase tracking-[0.14em] opacity-75">
                          {day.matchingWeekLabel || "No week"}
                        </p>
                      </button>
                    ))}
                  </div>
                </motion.div>
              ) : null}
            </AnimatePresence>
          </div>
        </div>
      </section>

      {loading ? (
        <div className="space-y-3">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-24 rounded-2xl bg-slate-100 dark:bg-slate-800" />
          ))}
        </div>
      ) : error ? (
        <div className="rounded-2xl border border-red-200 dark:border-rose-500/20 bg-red-50 dark:bg-rose-500/10 p-6 text-sm text-red-600 dark:text-rose-300">{error}</div>
      ) : weeks.length > 0 ? (
        <div className="space-y-3">
          {weeks.map((week, index) => (
            <motion.button
              key={week.weekEnd}
              type="button"
              onClick={() => setSelectedWeekEnd(week.weekEnd)}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.2, delay: index * 0.04 }}
              className="w-full text-left rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-transparent p-5 transition-all hover:border-slate-300 dark:hover:border-slate-700 hover:shadow-md group"
            >
              <div className="flex items-center justify-between gap-4">
                <div className="flex items-center gap-4">
                  <div className={cn(
                    "flex h-10 w-10 items-center justify-center rounded-xl border",
                    week.topSeverity === "green"
                      ? "border-emerald-200 dark:border-emerald-500/20 bg-emerald-50 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                      : week.topSeverity === "yellow"
                        ? "border-amber-200 dark:border-amber-500/20 bg-amber-50 dark:bg-amber-500/10 text-amber-600 dark:text-amber-400"
                        : "border-red-200 dark:border-red-500/20 bg-red-50 dark:bg-red-500/10 text-red-600 dark:text-red-400"
                  )}>
                    <Calendar className="h-4 w-4" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-slate-900 dark:text-white">
                      {formatWeekRange(week.weekStart, week.weekEnd)}
                    </p>
                    <p className="mt-1 text-xs text-slate-400 dark:text-slate-500">
                      {week.days.length} days analyzed
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <div className="hidden sm:flex items-center gap-4 text-xs text-slate-400 dark:text-slate-500">
                    <span className="flex items-center gap-1">
                      <MessageSquare className="h-3 w-3" /> {week.totalFeedback}
                    </span>
                    <span className="flex items-center gap-1">
                      <AlertTriangle className="h-3 w-3" /> {week.totalIssues}
                    </span>
                  </div>
                  <ArrowUpRight className="h-4 w-4 text-slate-300 dark:text-slate-600 transition group-hover:text-slate-600 dark:group-hover:text-white" />
                </div>
              </div>

              {/* Mini health bar */}
              <div className="mt-3 flex h-1.5 gap-0.5 rounded-full overflow-hidden">
                {week.days.map((d) => (
                  <div
                    key={d.date}
                    className={cn(
                      "flex-1 rounded-full",
                      d.severity === "green" ? "bg-emerald-400" : d.severity === "yellow" ? "bg-amber-400" : "bg-red-400"
                    )}
                  />
                ))}
              </div>
            </motion.button>
          ))}
        </div>
      ) : (
        <div className="rounded-2xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-transparent p-6 text-sm text-slate-500 dark:text-slate-400">
          No report data available yet. AgenticPulse will generate weekly reports once enough data flows through the system.
        </div>
      )}
    </div>
  );
}
